### ISSUE TITLE
last version that builds successfully

### ISSUE THREAD

**Issue by smherwig** [jbangert/nail#3] opened 2015-04-02 17:10 UTC
Hi, I'm a graduate student at UMD and using NAIL for a class project.  It looks really cool.

I cloned the most recent version and successfully built nail.  I started writing an HTTP parser, but, when compiling it, the linker complains of an undefined reference to parse_request(NailArena_*, NailStream).  (request is a struct I have in http.nail)

It looks like the signature for parse_request used to be generated as parse_http(NailArea *, uint8_t *, ssize_t) (i.e., took a buffer); but now the signature is parse_foo(Nail_Arena *, NailStream *).  Correct me if I'm wrong, but it doesn't look like all of the NailStream code has been written.

What was the last version that was just in C, before introducing the C++ templating?

Thanks

**Comment by jbangert** [comment] 2015-04-02 18:10
Hello,

nice to hear from you! The old 'c-style' code generator is still in the 
github - just 'ln -s nail cnail' and invoke nail as cnail. For an 
example using C++, look at /examples/dns_cpp which uses NailMemStream 
(include include/nail/memstream.hh). The issue is that the generator 
code will be in C no matter what (I hacked together most of the C++ 
support to do IPv6 better and support different types of input streams).

A lot of transforms haven't been ported and the build system in general 
is a bit wonky - sorry about that.

Regards,
Julian

**Comment by jbangert** [comment] 2015-04-23 17:37
Did not hear anything else - I am assuming you made it work with cnail?

**Closed by jbangert** 2015-04-23 17:37 UTC
